version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: crime_rate_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: crime-rate
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local